brew "atuin"
brew "automake"
brew "bash"
brew "bash-completion"
brew "carapace"
brew "clang-format"
brew "colordiff"
brew "coreutils"
brew "dive"
brew "gnutls"
brew "ffmpeg"
brew "findutils"
brew "flock"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "go"
brew "hyperfine"
brew "jq"
brew "libgit2"
brew "lua"
brew "mpv"
brew "mtr"
brew "neovim"
brew "node@20"
brew "p7zip"
brew "pandoc"
brew "pipx"
brew "ripgrep"
brew "ruby@3.1"
brew "rust"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "tig"
brew "tree"
brew "uv"
brew "w3m"
brew "wget"
brew "wordnet"
brew "yarn"
brew "yq"
brew "yt-dlp"
brew "zoxide"

cask "bitwarden"
cask "cherry-studio"
cask "font-fira-code-nerd-font"
cask "font-maple-mono"
cask "hammerspoon"
cask "iina"
cask "itsycal"
cask "kitty"
cask "only-switch"
cask "raycast"
cask "superlist"
cask "wechat"

# Per host setup
if `hostname -s`.strip == "Bragg"
  brew "helm"
  brew "fluent-bit"
  brew "terraform"
  cask "session-manager-plugin"
  cask "zulu@17"
end

if `hostname -s`.strip == "Feynman"
  brew "deno"
  brew "libpq"
  brew "node"
  brew "supabase"
  brew "tw93/tap/mole"
  cask "docker-desktop"
  cask "steam"
  cask "zoom"
end
