#!/usr/bin/env bash
#
# Author:         Kai Xia <xiaket@gmail.com>
# Filename:       gftp.sh
# Date created:   2014-11-03 13:03
# Last modified:  2014-11-03 14:29
# Modified by:    Kai Xia <xiaket@gmail.com>
#
# Description:
# 
# Changelog:
# 

pid=`pgrep lftp`

if [ "x$pid" != "x" ]
then
    socket="/Users/xiaket/.lftp/bg/dirac-$pid"
    echo "lftp is already running, attaching to it."
    lftp -e "attach $pid" torrent:G4009@192.168.34.33/ok
else
    lftp torrent:G4009@192.168.34.33/ok
fi
