# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Doc link: https://docs.vagrantup.com.

  # Use Debian 8 as base image.
  config.vm.box = "ubuntu/bionic64"

  # hostname of this VM
  config.vm.hostname = "neo"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # name of the vm
    vb.name = "neo"

    # resouce allocations.
    vb.memory = "3072"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01xiaket &&
    echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/01xiaket &&
    apt update &&
    apt purge -y command-not-found command-not-found-data ftp ntfs-3g vim* &&
    apt upgrade -y &&
    apt install -y python3-pip neovim lftp python3-setuptools golang procmail &&
    pip3 install -U pip &&
    pip install requests pipenv black neovim icdiff ptpython sh
  SHELL

  $user_script = <<-SCRIPT
    mkdir -p ~/.config/ ~/.xiaket/var/{log,run,tmp} ~/.xiaket/share/github &&
    cd ~/.xiaket/share/github &&
    if [ ! -d ~/.xiaket/share/github/etc ]
    then
      git clone https://github.com/xiaket/etc.git &&
      ln -sf ~/.xiaket/share/github/etc ~/.xiaket/etc &&
      ln -sf ~/.xiaket/etc/bashrc ~/.bashrc &&
      ln -sf ~/.xiaket/etc/gitconfig ~/.gitconfig &&
      ln -sf ~/.xiaket/etc/inputrc ~/.inputrc &&
      ln -sf ~/.xiaket/etc/pythonrc ~/.pythonrc &&
      ln -sf ~/.xiaket/etc/ptpython ~/.ptpython &&
      ln -sf ~/.xiaket/etc/vim ~/.vim &&
      mkdir -p ~/.vim/backup &&
      ln -sf ~/.xiaket/etc/vim ~/.config/nvim &&
      ln -sf ~/.xiaket/etc/vim/init.vim ~/.vimrc &&
      ln -sf ~/.xiaket/share/github ~/.GITHUB &&
      cd ~/.xiaket/etc/go && go build -o ../bin/my_prompt my_prompt.go
    else
      cd ~/.xiaket/etc && git pull
    fi
    curl -sfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    mkdir -p ~/.xiaket/alt/etc && echo -n "export COLOR_LAST_GOOD=51\nexport COLOR_LAST_FAIL=199\nexport BASH_COMPLETION_DIR=/usr/share/bash-completion/completions" > ~/.xiaket/alt/etc/bashrc
  SCRIPT

  config.vm.provision "shell", privileged: false, inline: $user_script

end
