# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Doc link: https://docs.vagrantup.com.

  # Use ubuntu 2104 as base image.
  config.vm.box = "ubuntu/hirsute64"

  # hostname of this VM
  config.vm.hostname = "ubuntu"

  config.vm.provider "virtualbox" do |vb|
    # name of the vm
    vb.name = "ubuntu"

    # resouce allocations.
    vb.memory = "4096"
    vb.cpus = 2
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
    end
  end

  # setup sync
  config.vm.synced_folder ENV['HOME'], "/mac"

  config.vm.provision "shell", inline: <<-SHELL
    echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01xiaket &&
    echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/01xiaket &&
    apt update &&
    apt purge -y command-not-found ftp ntfs-3g vim* cloud-init &&
    apt autoremove -y &&
    echo "Done with System setup."
  SHELL

  config.vm.provision "shell", path: "ubuntu.sh", privileged: true
end
