# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "ubuntu"

  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "max"
    qe.memory = "8G"
    qe.smp = "cpus=2,sockets=1,cores=2,threads=1"
    qe.net_device = "virtio-net-pci"
    qe.extra_qemu_args = %w(-accel tcg,thread=multi,tb-size=512)
    qe.qemu_dir = "/usr/local/share/qemu"
  end

  config.vm.synced_folder "/usr/local/share/qemu", "/mnt", type: "rsync"
  config.vm.synced_folder ".", "/vagrant", type: "smb", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01xiaket &&
    echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/01xiaket &&
    apt update &&
    apt purge -y command-not-found ftp ntfs-3g vim* cloud-init &&
    apt autoremove -y &&
    echo "Done with System setup."
  SHELL

  config.vm.provision "shell", path: "ubuntu.sh", privileged: true
end
