# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Doc link: https://docs.vagrantup.com.

  # Use ubuntu 2104 as base image.
  config.vm.box = "xiaket/freebsd-base"

  # hostname of this VM
  config.vm.hostname = "freebsd"

  config.vm.provider "virtualbox" do |vb|
    # name of the vm
    vb.name = "freebsd"

    # resouce allocations.
    vb.memory = "4096"
    vb.cpus = 2
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
    end
  end

  # setup sync
  config.vm.synced_folder ENV['HOME'], "/mac"
end
